language: node_js
node_js:
- '0.10'
before_script:
- npm install typescript -g
script: bash deploy.sh
branches: "-master"
env:
  global:
  - secure: d22Ovo77Z4aOcM+4m7ToOKCEgxyuG94gbpKSI7ccM1kPFbSEORLN+Xa743qeIFY9xObWRWOBTPJMF3HvElwuShJb9jv10hO3N5tuHZMWE7Qv+rnN5uzPIpSnHey7r4Yl6rPGL83Dc108cU4AJog6X1JW2XO5gayuQIK8vEf49TI=
  - secure: pbDzOwM4lh6jQqg7eAYnEosjWrmCTr2zDR1hc3o11xMuf19S3BDoFhkwNrTSYLSb/tkIuRbqSbtwhwbeuOAH7g8v/DNNz2vK53abZHt2MtDsBNvi0+jCh7cQq3hRppNG3SNRLAJ6rnKJi43mwnlC7jilW5hMY+tP3NblorUBSLA=
  - secure: BzM+lZsDUKuucTkDeXa3l+hzc4KfT6YLY3BJO0PxiINuRTzn24kKNmCxZzaQu5kltwYq0p+CzkbKA/Bbx5MAgD46VHEzi28eveOKoO884AykTXp5w6oGOD9cBfymusTj1SKob1Wb5AGmLij2wdP3TcbxB2X8aID5dnDA24w77y8=
